### ISSUE TITLE
Setup ucsc-fus for AuthN

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/data-store#20]
* need to migrate instance of dcp-fus -> ucsc-fus (ideally this information would be saved in ucsc-ci.org
* need to configure auth0 with new dev instance. (look at API section of auht0) 
* need to save configurations for fusillade into ucsc-ci.org

**Comment by chmreid** [comment]
Will this require forking HumanCellAtlas/dcp-fusillade repo to DataBiosphere/ucsc-fusillade? Will we need to fork HumanCellAtlas/fusillade as well?

**Comment by amarjandu** [comment]
@chmreid yes, fus. has already been forked on my local machine, im waiting on access to a CI/CD system to i can upload branches with our configs up.

**Comment by amarjandu** [comment]
* [ ]  need to setup oauth audience correctly for dev stage
