### ISSUE TITLE
Use presigned URLs by default in getfile and getbundle

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/data-store#3]
We should just reverse the defaults here instead of removing cloud native URLs. Make presingned URLs be the default.

**Comment by natanlao** [comment]
After discussing with @kozbo and @amarjandu, I am closing this issue with no PR. The DSS already implements the functionality requested:
* `GET /file/{uuid}` returns presigned URLs by default (i.e., if `directurls` is not specified, see [here](https://github.com/DataBiosphere/data-store/blob/e8c3efb44079165db6b4f13ad3a1783fb635909b/dss/api/files.py#L104))
* `GET /bundle/{uuid}` does not return URLs by default, but will return a cloud native URL or a presigned URL if one of them is explicitly specified. (See [here](https://github.com/DataBiosphere/data-store/blob/e8c3efb44079165db6b4f13ad3a1783fb635909b/dss/api/bundles/__init__.py#L59))
