### ISSUE TITLE
[SPIKE] Evaluate Options for AuthN/Z 

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/data-store#53]
The DSS needs a documented way for operators to add in authN/Z services to their implementation. Currently the setup cannot be found within the README, and has to be inferred from previous implementations / configurations. 

The goal of the spike is to identify an authN/Z solution that can be plug-n-play with the system.

- flexible authN configurations (OIDC) 
- terraform-able (we want fast deployments :) )
- potentially something off the shelf (auth0, keycloak, SAM) or a combination
- documented if we come back 6 months from now, it should be straight forward for an operator to configure this again.

**Comment by amarjandu** [comment]
Auth0 has limited official Terraform support, but there is this community provider located: https://github.com/alexkappa/terraform-provider-auth0
This would allow easier infra management...
- Auth0 has easier to configure systems for authZ https://auth0.com/docs/api/authorization-extension
- scopes for access can be set at the application level, then assigned to roles
- easy to get federated access to a google application 
- javascript rules can be flexed to add claims to the jwt token https://auth0.com/docs/tokens/concepts/jwt-claims this would align with the oidc_claims that the cli tooling uses
- need to figure out management of users in groups. manually managing the auth0 instance would be OK, but having something simple to use like [dcp-infra](https://github.com/HumanCellAtlas/dcp-infra) would be easier to manage

**Comment by chmreid** [comment]
someone has written a terraform provider for keycloak, one of the authN/authZ solutions we are considering: https://github.com/mrparkers/terraform-provider-keycloak

**Comment by chmreid** [comment]
Also of interest: https://github.com/danilop/LambdAuth

Need to do more research to figure out if this is a relevant solution though

**Comment by amarjandu** [comment]
Keycloak: 

- unofficial terraform support https://github.com/mrparkers/terraform-provider-keycloak
- potentially more cost due to running multiple instances of the service
- Unsure about aws lambda + keycloak; but there are other recommended solutions in the documentation about getting infra setup. 
- can support both authN (with google) and Roles + Groups + Users (AuthZ)

**Comment by amarjandu** [comment]
Fine Level Access Control:
- Using groups to manage this would be ideal, as users could be added to groups that have access to subsets of resources.
- Typical AuthZ systems don't have functionality in place for something like this, it could be managed simply with a dynamodb instance that has UUID/FQID w/ group access levels. (or SQL based system, if we wanted to have a database that store's referential integrity of data on some tables, and group access on tables)
- would need to think about structure of data fields UUID v. FQID. 
- simple to terraform (can setup backups here too for ddb, not sure about rds backups) 
- can potentially be setup for working on deletion RFC if using a RDS, this would allow for less managed infra overall
- there might need to be some research into how to handle errors here, or if the DB drops a request, what does that look like? SQS -> RDS/DDB consumer? might be a question for @xbrianh

**Comment by chmreid** [comment]
Based on outcome of 2020-02-14 architecture meeting, we will be implementing an AuthN/AuthZ system that looks like the following:

* AuthN provided by Auth0
* AuthZ provided by Auth0's authorization extension (offers users/groups/roles)
* Fine-level access control (FLAC) provided via DynamoDB lookup table
    * DynamoDB table has keys (UUIDs) and values (users/groups/roles allowed to access resources)
* API endpoints are decorated with a security function that checks:
    * Is the given UUID protected by an ACL?
    * If so, is the requester principal allowed to access the given resource?
* Terraforming of resources:
    * Terraforming of Auth0 resources is provided by scripts in https://github.com/DataBiosphere/data-store-auth
    * Terraforming of FLAC table is provided by scripts in `infra/` folder of data-store repo

**Comment by chmreid** [comment]
Closing this issue, as the spike has served its purpose and we've decided on a path forward
