### ISSUE TITLE
Auth0 Teraforming

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/data-store#69]
Need to use community Auth0 provider

**Comment by amarjandu** [comment]
- [x] need to make updates to common.mk to ensure operator has GO installed + provider 
 - [ ] need to update toilspark runner 
 - [x] need to update build_deploy_config.sh to support provider
- [ ] update infra/Makefile to not deploy auth by default when running commands, must be done manually

**Comment by amarjandu** [comment]
Auth0 Tenant has been upgraded to OSS account, domain for the tenant has been pointed to `dev.auth.ucsc-cgp-redwood.org` this should allow google-IdP to work

**Comment by chmreid** [comment]
#120 updates data store tests to use the new values in DataBiosphere/data-store-auth

**Comment by chmreid** [comment]
I think this is ready to close
