### ISSUE TITLE
FLAC: Terraform Infra

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/data-store#72]

**Comment by chmreid** [comment]
Any files to terraform FLAC infra belong in DataBiosphere/data-store-auth

That repo is intended specifically for auth-related infrastructure

**Comment by chmreid** [comment]
Issue moved to [DataBiosphere/data-store-auth #10](https://github.com/DataBiosphere/data-store-auth/issues/10) via [**ZenHub**](https://www.zenhub.com/)
