### ISSUE TITLE
Create a developer vignette around eventing 

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/data-store#79]

**Comment by chmreid** [comment]
@melainalegaspi @kozbo This ticket needs a bit more definition, and raises some additional questions about the existing data consumer vignettes.

* Where should this vignette go?
* If this should go in the data-consumer-vignettes repo, that repo is owned by HCA - so should we fork that repo to DataBiosphere?
* If we should fork it and point it at our new data store, how should we deal with the fact that the notebooks are using an empty data store so most of the vignettes will no longer work?
* What is the scope of the developer vignette?
    * Should probably have multiple examples
    * Search for bundles/files by UUID
    * Search for bundles/files by filename or file type (*.fastq.gz)
    * Search for bundles/files/projects (fuzzy) matching a search term (e.g., "liver")
    * Search for data by sequencing methodology (e.g., 10x)
* What is the definition of done for this vignette?

**Comment by kozbo** [comment]
I don't want to create a vignette repo here, and there is not much use in producing example code for a data store that doesn't have any data. We can drop the level of importance of this. We can help users when they need it. I am closing this.
