### ISSUE TITLE
Review licenses for data store and data biosphere

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/data-store#8]

**Comment by kozbo** [comment]
Leaving as MIT license for now.

**Comment by kozbo** [comment]
From what I can tell from reading the docs on the [UCSC IP Open Source Software site](https://security.ucop.edu/resources/open-source-software-licensing.html) it is fine to leave this as an MIT license. We should create another level of nesting with UCSC copyright at the top (but leaving in the HCA license too). 

[Chart](https://security.ucop.edu/files/documents/resources/oss-chart.pdf)
