### ISSUE TITLE
Auth0 OSS Account

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/data-store#92]
follow up with taylor.sepulveda@auth0.com  for OSS account.

- [x] add auth0 badge for the DSS

**Comment by chmreid** [comment]
Status update: still waiting for a response from Auth0.

I also opened a ticket with my account to prod them a bit more.

**Comment by chmreid** [comment]
Update from Auth0: "Our team should have this request done by the end of this day." (Realistically, it should be done sometime in the next few days.)

**Comment by chmreid** [comment]
This has been completed as of 2 PM Friday 2/21/20! woo hoo!!!

**Comment by amarjandu** [comment]
tenant now points to `dev.auth.ucsc-cgp-redwood.org`
